Lab2
pleshkovvli/15201-pleshkov pull request #2
Opened 2017-05-02 13:17 UTC by pleshkovvli

2017-05-19 04:02 UTC, levanovd requested changes

2017-05-19 04:02 UTC, levanovd commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/factory/CarStorage.java
> +    private Object viewLock = new Object();
final

2017-05-19 04:02 UTC, levanovd commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/factory/CarStorageController.java
> +
Запись в лог

2017-05-19 04:02 UTC, levanovd commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/factory/Initializer.java
> +    private static void parseConfig(Path configFilePath) throws BadParseException {
Это надо вынести в отдельный класс

2017-05-19 04:02 UTC, levanovd commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/factory/Supplier.java
> +                    System.err.println("Failed to cast: " + typeClass);
Писать в лог. Почему ловится `Exception`, а не более конкретный тип? Какой смысл продолжать работу, если такое случилось один раз?

2017-05-19 04:02 UTC, levanovd commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/pool/ThreadPool.java
> +                    break;
Можно `try-catch` просто вынести за цикл

2017-05-19 04:02 UTC, levanovd commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/factory/Main.java
> +            System.out.println(e.getMessage());
Писать в лог

2017-05-19 04:02 UTC, levanovd commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/factory/Initializer.java
> +            t.interrupt();
После этого надо дождаться завершения потоков с помощью `join()`

2017-05-19 04:02 UTC, levanovd commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/factory/FactoryLogger.java
> +class FactoryLogger implements Observer {
Надо использовать `log4j`

2017-05-19 04:02 UTC, levanovd commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/factory/Initializer.java
> +        threads = new Thread[dealersNumber + accessorySuppliersNumber + NUMBER_OF_THREADS];
`ArrayList`

2017-05-19 04:02 UTC, levanovd commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/factory/Main.java
> +            System.out.println(e.getMessage());
В случае, когда файл с конфигом не найден, ничего не пишется

2017-05-23 09:09 UTC, pleshkovvli commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/factory/CarStorage.java
> +    private Object viewLock = new Object();
Исправил

2017-05-23 09:09 UTC, pleshkovvli commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/factory/CarStorageController.java
> +
Добавил

2017-05-23 09:09 UTC, pleshkovvli commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/factory/Initializer.java
> +        threads = new Thread[dealersNumber + accessorySuppliersNumber + NUMBER_OF_THREADS];
Исправил

2017-05-23 09:09 UTC, pleshkovvli commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/factory/Initializer.java
> +    private static void parseConfig(Path configFilePath) throws BadParseException {
Исправил

2017-05-23 09:09 UTC, pleshkovvli commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/factory/Initializer.java
> +            t.interrupt();
Добавил

2017-05-23 09:09 UTC, pleshkovvli commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/factory/Supplier.java
> +                    System.err.println("Failed to cast: " + typeClass);
Исправил

2017-05-23 09:09 UTC, pleshkovvli commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/pool/ThreadPool.java
> +                    break;
Исправил

2017-05-23 09:10 UTC, pleshkovvli commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/factory/Main.java
> +            System.out.println(e.getMessage());
Добавил, исправил - пишется в лог и консоль

2017-05-23 09:10 UTC, pleshkovvli commented on lab2/src/ru/nsu/ccfit/pleshkov/lab2/factory/FactoryLogger.java
> +class FactoryLogger implements Observer {
Внутри log4j

2017-06-02 03:32 UTC, levanovd approved these changes

2017-06-02 03:33 UTC, levanovd commented
Принимается

2017-06-02 03:53 UTC, merged